version: '3'
services:
  web:
    build: .
    env_file: .env
    environment:
      - 'HOST=0.0.0.0'
    ports:
      - $DOCKER_COMPOSE_WEB_PORT:3000
    restart: unless-stopped
    depends_on:
      - postgres

  postgres:
    image: postgres:13
    environment:
      POSTGRES_PASSWORD: $DB_PASSWORD
      POSTGRES_USER: $DB_USERNAME
      POSTGRES_DB: $DB_DATABASE
    ports:
      - $DOCKER_COMPOSE_POSTGRES_PORT:5432
    restart: unless-stopped
    volumes:
      - /data/amocrm/postgres/var/lib/postgresql/data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
